title: Monthly
points:
  - 'Take, Share, and Export Cornell Style Notes'
  - 'Free 30 day trial, no commitment'
  - 'Autosave your notes as your write'
  - 'Upload Images to support your learning'
  - 'Search all of your notes for better recall'
  - 'Blur your notes for easier testing'
updated_by: fc563721-03e3-4aff-97cb-e536ec62cc36
updated_at: 1659249715
blueprint: plan_features
