title: Yearly
points:
  - 'Take, Share, and Export Cornell Style Notes'
  - 'All Features from Monthly plan with a 10% discount'
  - Autosave
  - 'Upload Images'
  - 'Search all of your notes'
  - 'Blur your notes for easier testing'
updated_by: fc563721-03e3-4aff-97cb-e536ec62cc36
updated_at: 1659249789
blueprint: plan_features
